<div data-bind="scope: 'Orderattachment'">
        <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "Orderattachment": {
                            "component": "Sp_Orderattachment/js/attachment",
                            "dataconfig": <?= $this->getAttachmentConfig() ?>,
                            "urlPDFImage": "<?php echo $this->getViewFileUrl('Sp_Orderattachment::images/pdf-icon.png'); ?>",
                            "urlOpenImage": "<?php echo $this->getViewFileUrl('Sp_Orderattachment::images/open-icon.png'); ?>"
                        }
                    }
                }
            }
        }
</script>